import React, { useEffect } from 'react';
import styled from 'styled-components'

const Container = styled.div`
`

const Body = styled.div`
    over-flow:scroll;
    // margin-top:3rem;
    padding:1rem;
`
const Title = styled.span`
    font-weight:bold
`
const PolicyCN = () => {
    useEffect(() => {
        document.title = "policy | GOOChat"
    }, [])
    return (
        <Container>
            <Body>
                <h1><Title>GooChat Privacy Policy</Title></h1>
                <h3><Title>1. Introduction</Title></h3>
                <p>This Privacy Policy sets out how we, GooChat SDN. BHD. <Title>(&ldquo;GooChat&rdquo;)</Title>, use and protect your personal data that you provide to us, or that is otherwise obtained or generated by us, in connection with your use of our cloud-based messaging services (the <Title>&ldquo;Services&rdquo;</Title>). For the purposes of this Privacy Policy, <Title>&lsquo;we&rsquo;</Title>, <Title>&lsquo;us&rsquo;</Title> and <Title>&lsquo;our&rsquo;</Title> refers to GooChat, and <Title>&lsquo;you&rsquo;</Title> refers to you, the user of the Services.</p>
                <h4><Title>1.1 Privacy Principles</Title></h4>
                <p>GooChat has two fundamental principles when it comes to collecting and processing private data:</p>
                <ul>
                    <li>We don't use your data to show you ads.</li>
                    <li>We only store the data that GooChat needs to function as a secure and feature-rich messaging service.</li>
                </ul>
                <h4><Title>1.2. Terms of Service</Title></h4>
                <p>This Privacy Policy forms part of our Terms of Service, which describes the terms under which you use our Services and which are available at <Title>https://app.goochat.net/term/en</Title> This Privacy Policy should therefore be read in conjunction with those terms.</p>
                <h4><Title>1.3. Table of Contents</Title></h4>
                <p>This Privacy Policy explains the following:</p>
                <ul>
                    <li>the legal basis for processing your personal data.</li>
                    <li>what personal data we may collect from you.</li>
                    <li>how we keep your personal data safe.</li>
                    <li>what we may use your personal data for.</li>
                    <li>who your personal data may be shared with.</li>
                    <li>your rights regarding your personal data.</li>
                </ul>
                <h3><Title>2. Legal Ground for Processing Your Personal Data</Title></h3>
                <p>We process your personal data on the ground that such processing is necessary to further our legitimate interests (including: <em>(1)</em> providing effective and innovative Services to our users; and <em>(2)</em> to detect, prevent or otherwise address fraud or security issues in respect of our provision of Services), unless those interests are overridden by your interest or fundamental rights and freedoms that require protections of personal data.</p>
                <h3><Title>3. What Personal Data We Use</Title></h3>
                <h4><Title>3.1. Basic Account Data</Title></h4>
                <p>GooChat is a communication service. You provide your mobile number and basic account data (which may include profile name, profile picture and about information) to create a GooChat account.</p>
                <p>To make it easier for your contacts and other people to reach you and recognize who you are, the screen name you choose, your profile pictures, and your <a href="https://telegram.org/faq#usernames-and-t-me">username</a> (should you choose to set one) on GooChat are always public. We don't want to know your real name, gender, age or what you like.</p>
                <p>We do <Title>not</Title> require your screen name to be your real name. Note that users who have you in their contacts will see you by the name they saved and not by your screen name. This way your mother can have the public name 'Johnny Depp' while appearing as 'Mom' to you and as 'Boss' to her underlings at work (or the other way around, depending on how these relationships are structured).</p>
                <h4><Title>3.2. Your E-mail Address</Title></h4>
                <p>When you enable email sign in You can choose to set up a password recovery email. This address will be used to send you a password recovery code if you forget it. That's right: no marketing or nonsense. "We miss you"</p>
                <h4><Title>3.3. Your Messages</Title></h4>
                <h5><Title>3.3.1. Cloud Chats</Title></h5>
                <p>GooChat is a cloud service. We store messages, images, videos and documents from your cloud chat on our servers. so that you can access your data from any of your devices</p>
                <h5><Title>3.3.2. Public Chats</Title></h5>
                <p>In addition to private messages, GooChat also supports public channels and public groups. All public chats are cloud chats (see <a href="https://telegram.org/privacy#3-3-1-cloud-chats">section 3.3.1 above</a>). Like everything on GooChat, the data you post in public communities is encrypted, both in storage and in transit &mdash; but everything you post in public will be accessible to everyone.</p>
                <h5><Title>3.4. Phone Number and Contacts</Title></h5>
                <p>Phone Number and Contacts</p>
                <p>GooChat uses phone numbers as unique identifiers so that it is easy for you to switch from SMS and other messaging apps and retain your social graph. We ask your permission before syncing your contacts.</p>
                <p>We store your up-to-date contacts in order to notify you as soon as one of your contacts signs up for GooChat and to properly display names in notifications. We only need the number and name (first and last) for this to work and store no other data about your contacts.</p>
                <p>Our automatic algorithms can also use anonymized sets of phone numbers to calculate the approximate number of potential contacts an unregistered phone number may have on GooChat. When you open the 'Invite friends' interface, we display the resulting statistics next to your contacts to give you an idea of who could benefit most from joining GooChat.</p>
                <p>You can always stop syncing contacts or delete them from our servers in Settings &gt; Contact</p>
                <h4><Title>3.5. Location Data</Title></h4>
                <p>This location information is treated like any other message. If you specify your location in your official account profile, GooChat will use your information to show your location to the users you share with. even if the app is closed As long as you enable these optional features</p>
                <h3><Title>4. Keeping Your Personal Data Safe</Title></h3>
                <h4><Title>4.1. Storing Data</Title></h4>
                <p>Your data is stored in data centers. These are third-party provided data centers in which GooChat rents a designated space. However, the servers and networks that sit inside these data centers and on which your personal data is stored are owned by GooChat. As such, we do not share your personal data with such data centers. All data is stored heavily encrypted so that local Telegram engineers or physical intruders cannot get access.</p>
                <h4><Title>4.2.Retention</Title></h4>
                <p>Unless stated otherwise in this Privacy Policy, the personal data that you provide us will only be stored for as long as it is necessary for us to fulfill our obligations in respect of the provision of the Services.</p>
                <h3><Title>5. Processing Your Personal Data</Title></h3>
                <h4><Title>5.1. Our Services</Title></h4>
                <p>GooChat is a cloud service. We will process your data to deliver your cloud chat history, including messages, media and files, to any devices of your choosing</p>
                <h4><Title>5.2. Safety and Security</Title></h4>
                <p>GooChat supports a large community where we have to investigate violations and violations of the Terms of Service. GooChat has a large number of users. This makes it a lucrative target for spammers. To improve the security of your account As well as preventing spam, abuse, and other violations of our Terms of Service, we may collect metadata such as your IP address, the devices and GooChat apps you use, username change history, etc., if collected. This eye is stored for a maximum of 12 months.</p>
                <h4><Title>5.3. Spam and Abuse</Title></h4>
                <p>To prevent phishing, spam, and other types of abuse. And for violations of the GooChat Terms of Service, our moderators may review messages reported by recipients to them. If a spam report about a message you send is verified by our moderators. Your account may be restricted from contacting strangers - temporarily or permanently. You can send a request using the report function for contacts and messages, In case of serious violations Your account may be banned. We may use automated algorithms to analyze messages in cloud chat to stop spam and phishing.</p>
                <h4><Title>5.4. Cross-Device Functionality</Title></h4>
                <p>We may also store some aggregated metadata to create GooChat features that work across all your devices.</p>
                <h4><Title>5.5. No Ads Based on User Data</Title></h4>
                <p>Unlike other services, we don't use your data for ad targeting or other commercial purposes. GooChat only stores the information it needs to function as a secure and feature-rich cloud service.</p>
                <p>GooChat offers a tool for advertisers to promote their messages in public one-to-many channels, but these sponsored messages are based solely on the topic of the public channels in which they are shown. No user data is mined or analyzed to display ads or sponsored messages.</p>
                <h3><Title>6. Who Your Personal Data May Be Shared With</Title></h3>
                <h4><Title>6.1. Other GooChat Users</Title></h4>
                <p>Other users of our Services with whom you choose to communicate with and share certain information, who may be located outside. Note that by entering into the Terms of Service and choosing to communicate with such other users of GooChat, you are instructing us to transfer your personal data, on your behalf, to those users in accordance with this Privacy Policy. We employ all appropriate technical and organizational measures (including encryption of your personal data) to ensure a level of security for your personal data that is appropriate to the risk.</p>
                <h4><Title>7. Your Rights Regarding the Personal Data You Provide to Us</Title></h4>
                <h4><Title>7.1. Your Rights</Title></h4>
                <p>Under applicable data protection legislation, in certain circumstances, you have rights concerning your personal data. You have a right to: <em>(1)</em> request a copy of all your personal data that we store and to transmit that copy to another data controller; <em>(2)</em> delete (see section 8 below) or amend your personal data; <em>(3)</em> restrict, or object to, the processing of your personal data; <em>(4)</em> correct any inaccurate or incomplete personal data we hold on you; and <em>(5)</em> lodge a complaint with national data protection authorities regarding our processing of your personal data.</p>
                <h4><Title>7.2. Exercising Your Rights</Title></h4>
                <p>If you wish to exercise any of these rights, kindly contact us using the details in section 10 below.</p>
                <h4><Title>7.3. Data Settings</Title></h4>
                <p>You can control how your data is used (e.g. delete synced contacts) in Settings &gt; Contacts (using one of our mobile apps).</p>
                <p>Sadly, if you don't agree with GooChat's minimum requirements, we can't provide it to you. You can delete your GooChat account by going to Settings &gt; Account</p>
                <h3><Title>8. Deleting data</Title></h3>
                <h4><Title>8.1. Accounts</Title></h4>
                <p>If you want to delete your account You can do it in Setting &gt; Account, Deleting your account will delete all messages, media, contacts, and other data you have stored in the GooChat cloud. This action must be verified through your GooChat account and cannot be cancelled.</p>
                <h4><Title>8.2. Messages</Title></h4>
                <ul>
                    <li>in cloud chat You can choose to delete the message for all participants at least 24 hours after sending, otherwise deleting the message will delete it from your message history. This means that a copy will be on the server as part of your partner's message history. As soon as your partner removes it too Data will be lost forever.</li>
                    <li>in this version Either party can choose to clear all chat history for both parties. In this case, the app will be instructed to delete all messages in that chat. No matter how many messages are retained by one participant In a group, deleting a message deletes the message for all participants.</li>
                </ul>
                <h4><Title>8.3. Self-Destructing Messages</Title></h4>
                <p>Messages can now self-destruct when the countdown starts. When the message is complete and when the countdown timer is up The app will be instructed to delete the message either Private or group chat.</p>
                <h3><Title>9. Changes to this Privacy Policy</Title></h3>
                <p>We will review and may update this Privacy Policy from time to time. Changes to this Privacy Policy will become effective when we post the revised Privacy Policy on this page. https://app.goochat.net/policy/en Please check our website often. to view updates or changes to our Privacy Policy. which we will briefly describe below.</p>
                <p>This document was last updated on April 5, 2022.</p>
                <p>Significant changes to this Privacy Policy will be notified to you via GooChat.</p>
                <ol>
                    <li><Title> Questions and concerns</Title></li>
                </ol>
                <p>If you have any questions about privacy and our data policies, please contact our oochat ID: goochatofficial or E-mail: goochat-admin@goochat.chat. which we will answer at the earliest opportunity.</p>
            </Body>
        </Container>
    )
}
export default PolicyCN;